### ISSUE TITLE
Can this work on rhcloud.com?

### ISSUE THREAD

**Issue by edmcdonagh** [commonsmachinery/openshift-rabbitmq-cart#3]
@anefassa, @petli, @caruccio - does this work on rhcloud.com/openshift.com? Or just when you install the openshift software yourself?

As far as I can see, you cannot simply `yum install erlang` can you?

I'd like to be told I'm wrong :-)

**Comment by caruccio** [comment]
AFAIK, Erlang is not installed on openshift online. You may try to compile it yourself (or extract from EPEL's RPM - doesn't seem a pleasant task) and ship with this cartridge.

Please let me known if you succeeded.

**Comment by edmcdonagh** [comment]
Thanks for the clarification @caruccio - I think that task is beyond me, particularly for what I need. I'll investigate using https://www.cloudamqp.com/ instead I think.

**Comment by caruccio** [comment]
I've found this cart https://github.com/wozniakjan/erlcart
It may be a good start point.
